### ISSUE TITLE
Regarding checkpoint

### ISSUE THREAD

**Issue by Anirudh257** [Echo0125/Memory-and-Anticipation-Transformer#1]
Congratulations on your fantastic work and all the best for your presentation. I wanted to know:

1) Link to the supplementary.

2) Can you release the checkpoints for EK-100 and THUMOS online action detection? 

3) To reproduce EK-100 and THUMOS online action detection, what changes do I need to make to the code? And any other change to config is needed?

4) How is the **work-memory sample rate** and **long-memory sample rate** decided in https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/b84186438d748c599146a512a089ddc6a93a1761/configs/EK100/MAT/mat_long_64_work_5_kinetics_1x.yaml#L18?

**Comment by Echo0125** [comment]
Thank you for your interest in our work.
1. We have submitted supplementary materials, you can find it after this work is published;
2. MAT is capable of inferring both oad and aa results in a single run. You can use the inference code mentioned in README to obtain both results using the same checkpoint;
3. You can directly use the provided configs and codes to reproduce MAT's performance;
4. We directly borrowed from [lstr](https://github.com/amazon-science/long-short-term-transformer) and [TeSTra](https://github.com/zhaoyue-zephyrus/TeSTra).

**Comment by Anirudh257** [comment]
Hi, thanks for your response. I believe, setting **ANTICIPATION_SECONDS** to 0 will fix the problem?

https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/b84186438d748c599146a512a089ddc6a93a1761/configs/THUMOS/MAT/mat_long_256_work_8_kinetics_1x.yaml#L23

Waiting for your supplementary :) Had doubts about MixClip++.

**Comment by Echo0125** [comment]
There is no need to set anticipation_seconds to 0, MAT will output the results of oad and aa at the same time after running a single inference.

**Comment by Anirudh257** [comment]
Thanks!

**Comment by fake-warrior8** [comment]
> There is no need to set anticipation_seconds to 0, MAT will output the results of oad and aa at the same time after running a single inference.

Is it the default setting for traditional oad experiments? i.e., training predicts actions 2 seconds from now and testing predicts the actions at the current time?
