### ISSUE TITLE
HDD and TVSeries dataset

### ISSUE THREAD

**Issue by mugenggeng** [Echo0125/Memory-and-Anticipation-Transformer#10]
I'm sorry to bother you. I'm very interested in your research. I would appreciate it if you could provide us with features about HDD and TVSeries.

**Comment by Echo0125** [comment]
Sorry, I cannot release the features due to the copyright. You can apply for the HDD and TVSeries data and extract the features yourself.

**Comment by 04beckman** [comment]
@mugenggeng Have you solved this problem? Could······ you share that?

**Comment by mugenggeng** [comment]
@04beckman Sorry, unable to publish due to copyright reasons
