### ISSUE TITLE
The project cannot be run

### ISSUE THREAD

**Issue by picajcjj** [Echo0125/Memory-and-Anticipation-Transformer#11]
Sorry to bother you.,I'd like to ask what the config_file is needed to run the program.,The program error is because I didn't specify the path of the config_file.,Can you please help me solve it?Thank you.

**Comment by Echo0125** [comment]
You can use the config in the [config folder](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/tree/main/configs) for training. Here is an example command you can run:

```bash
python tools/train_net.py --config_file ./configs/THUMOS/MAT/mat_long_256_work_8_anet_1x.yaml --gpu 0
