### ISSUE TITLE
Request for the extracted features of TV Series and HDD datasets

### ISSUE THREAD

**Issue by Prism-hua** [Echo0125/Memory-and-Anticipation-Transformer#12]
I have seen that the author cannot share the extracted features owing to the copyright. 
I would really appreciate it if anybody can share the pre-extracted features of TV Series and HDD with me or enlighten me with the detailed ways to extract the features myself. 

Hello @mugenggeng, sorry to bother, I have read about the [issue](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/issues/10)  you opened in request for the features, and I am wondering if you have finished the extraction. If yes, I sincerelly hope that you can share that with me, Thanks a lot!

**Comment by mugenggeng** [comment]
As you said, due to copyright reasons, I can't share it with you. Because these two data sets are not public.

**Comment by Prism-hua** [comment]
Thanks @mugenggeng and hello @Echo0125, I am aware of the fact that these two datasets should not be shared through the public internet, I have tried to apply for these datasets myself. But as published in the [readme](https://github.com/Echo0125/Memory-and-Anticipation-Transformer#data-preparation) file, ways to extract the features of HDD dataset and the Data Structure of HDD still remain unknown.
Could you please share me with the procedure or any tutorial that I can follow to extract the features of HDD dataset and reproduce the results on these two datasets?

**Comment by Echo0125** [comment]
Thanks for your interest in our work. As mentioned in the README, for TVSeries, you can refer to the steps in (LSTR) [https://github.com/amazon-science/long-short-term-transformer#data-preparation] and ( issue)[https://github.com/amazon-science/long-short-term-transformer/issues/2] for feature extraction; for HDD, you will get the corresponding sensor features after applying for the dataset, you can just follow the structure in (Data Structure)[https://github.com/Echo0125/Memory-and-Anticipation-Transformer?tab=readme-ov-file#data-structure] and add the corresponding information to (data_info)[https: //github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/main/data/data_info.json].

**Comment by Echo0125** [comment]
Thanks for your interest in our work. As mentioned in the README, for TVSeries, you can refer to the steps in [[LSTR)](https://github.com/amazon-science/long-short-term-transformer#data-preparation)](https://github.com/amazon-science/long-short-term-transformer#data-preparation) and [[issue](https://github.com/amazon-science/long-short-term-transformer/issues/2)](https://github.com/amazon-science/long-short-term-transformer/issues/2) for feature extraction; for HDD, you will get the corresponding sensor features after applying for the dataset, you can just follow the structure in [[Data Structure](https://github.com/Echo0125/Memory-and-Anticipation-Transformer?tab=readme-ov-file#data-structure)](https://github.com/Echo0125/Memory-and-Anticipation-Transformer?tab=readme-ov-file#data-structure) and add the corresponding information to [[data/data_info.json](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/issues/%5BMemory-and-Anticipation-Transformer/data/data_info.json%20at%20main%20%C2%B7%20Echo0125/Memory-and-Anticipation-Transformer%20(github.com)%5D(https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/main/data/data_info.json))]([Memory-and-Anticipation-Transformer/data/data_info.json at main · Echo0125/Memory-and-Anticipation-Transformer (github.com)](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/blob/main/data/data_info.json)).

**Comment by Echo0125** [comment]
Thanks for your interest in our work. For HDD, you will get the corresponding sensor features after applying for the dataset, you can just follow the structure in [Data Structure](https://github.com/Echo0125/Memory-and-Anticipation-Transformer?tab=readme-ov-file#data-structure) and add the corresponding information to [data/data_info.json](Memory-and-Anticipation-Transformer/data/data_info.json).

**Comment by Prism-hua** [comment]
Thanks for your timely response @Echo0125. Embarrassed to tell you that I am also having problems extracting features of TVSeries. As the [README](https://github.com/amazon-science/long-short-term-transformer?tab=readme-ov-file#data-preparation:~:text=For%20Kinetics%20pretrained%20features%2C%20we%20use%20the%20ResNet%2D50%20model%20for%20the%20RGB%20inputs.%20We%20recommend%20to%20use%20this%20checkpoint%20in%20MMAction2.%20We%20use%20the%20BN%2DInception%20model%20for%20the%20optical%20flow%20inputs.%20We%20recommend%20to%20use%20the%20model%20here.) of LSTR said, I should use MMAction2 and BN-Inception to get the RGB and optical flow inputs respectively, however, the urls of "checkpoint" and "here" does not work now, could please tell me what I should do to solve this? Thank you so much for your generous help!

**Comment by Prism-hua** [comment]
It seems that I have made a mistake, I should only use the checkpoints from MMAaction2,  and use ResNet-50 and BN-Inception network to extract the rgb and optical flow inputs respectively. But now the problem is that nither do I have access to the checkpoints, nor do I know how to build feature extraction network using the two structures. Could you please provide me with more detailed infomation? Words fail to express my gratitude!!

**Comment by Echo0125** [comment]
You can find the checkpoint in this branch [mmaction2_0.x](https://github.com/open-mmlab/mmaction2/tree/0.x/configs/recognition/tsn), just follow the file provided by mmaction2 to extract the feature: [feature_extractor](https://github.com/open-mmlab/mmaction2/blob/0.x/tools/data/activitynet/tsn_feature_extraction.py).
