### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by Prism-hua** [Echo0125/Memory-and-Anticipation-Transformer#13]
```
                anticipation_queries = self.pos_encoding(
                    self.final_query.weight[:self.cfg.MODEL.LSTR.ANTICIPATION_LENGTH
                                            :self.cfg.MODEL.LSTR.ANTICIPATION_SAMPLE_RATE, ...].unsqueeze(1).repeat(1,work_memories.shape[1], 1),
                    padding=self.work_memory_num_samples)
                work_memories = torch.cat((work_memories, anticipation_queries), dim=0)
```
Hello @Echo0125 , I have a another question about your code of MAT. In the code above, an *anticipation_queries* is concatenated with the *work_memories*. Could you please tell me what is the function of anticipation_queries, and why it is necessary to combine the *work_memories* and the *anticipation_queries*? Thanks so much!

**Comment by Echo0125** [comment]
MAT can perform oad and aa at the same time, after cat the anticipation_queries and work_memories together, mat can directly extract the corresponding token based on the timestamp for prediction. The performance can also be improved after combination.

**Comment by chcchc97** [comment]
but it is different from what you say in the paper, could you explain this situation? @Echo0125 
![Image](https://github.com/user-attachments/assets/7d498eb5-f81c-4425-9f81-b03845ad720b)
