### ISSUE TITLE
Questions about essays

### ISSUE THREAD

**Issue by sunzx11** [Echo0125/Memory-and-Anticipation-Transformer#15]
“We then employ NL learnable tokens QL ∈ R NL×D as the long-term memory queries and a weight-shared transformer decoder block to query Classifier each segment.”In it, the parameter NL is defined according to what？ “we use NF future queries QF ∈ RNF ×D and a transformer decoder block to query ME.”In it, the parameter NF is defined according to what？Thank you for your kind answers!

**Comment by Echo0125** [comment]
Sorry for the late reply.  For $N_L$, we just borrow it from [LSTR](https://arxiv.org/pdf/2107.03377). As for $N_F$, we conducted a series of ablation experiments in the paper to determine its final value.
