### ISSUE TITLE
about FPS

### ISSUE THREAD

**Issue by mugenggeng** [Echo0125/Memory-and-Anticipation-Transformer#16]
I am very sorry to bother you, but I would like to know how your FPS is calculated and why there is a problem with my calculation? I only calculated the FPS during the model inference period, not including the two-stream feature processing. I divided the total time by the sum of the lengths of all GT to get the FPS. Is there any problem with this?

**Comment by Echo0125** [comment]
Sorry for the late reply. We have provided the explanation in [this issue](https://github.com/Echo0125/MAT-Memory-and-Anticipation-Transformer/issues/14#issuecomment-2182844990), you can refer to it.
