### ISSUE TITLE
Project code issues

### ISSUE THREAD

**Issue by picajcjj** [Echo0125/Memory-and-Anticipation-Transformer#17]
Hello, how do I execute the two files eval_perframe.py and eval_perstage.py? Thank you for your answer

**Comment by Echo0125** [comment]
After inference, you can get the inference result stored in a pickle file; you can do both eval_perframe and eval_erstage by passing the file path.

**Comment by picajcjj** [comment]
Thanks for your reply, I checked the code and found that the code block for saving the pickle file in perframe_data_layers.py was commented

**Comment by picajcjj** [comment]
> 推理后，可以得到存储在泡菜文件中的推理结果;您可以通过传递文件路径来执行eval_perframe和eval_erstage。

Thanks for your reply, I checked the code and found that the code block for saving the pickle file in perframe_data_layers.py was commented

**Comment by picajcjj** [comment]
Thanks for your reply, I checked the code and found that the code block for saving the pickle file in perframe_det_batch_inference.py was commented
