### ISSUE TITLE
rekognition_online_action_detection包安装问题

### ISSUE THREAD

**Issue by LuYang-2023** [Echo0125/Memory-and-Anticipation-Transformer#18]
Traceback (most recent call last):

  File "tools/train_net.py", line 5, in <module>

    from rekognition_online_action_detection.utils.parser import load_cfg

ModuleNotFoundError: No module named 'rekognition_online_action_detection'。
我已经尝试了谷歌、百度、GPT等搜索方法，并阅读代码中的readme但未发现有相关内容，请您提供一些建议怎么安装rekognition_online_action_detection包。

**Comment by deadlykitten4** [comment]
import sys
sys.path.append("")

add your specific "path/to/src", which means that sys.path.append("path/to/src"), then you can solve this problem

**Comment by LuYang-2023** [comment]
> import sys sys.path.append("")
> 
> add your specific "path/to/src", which means that sys.path.append("path/to/src"), then you can solve this problem
I see. Thank you for your answer.
