### ISSUE TITLE
Issue about creating

### ISSUE THREAD

**Issue by JessieSun-lalala** [Echo0125/Memory-and-Anticipation-Transformer#2]
Thanks for your great work and sharing.

When I try to add modules in the original MAT framework, I find that only creating new modules without using them, the detection results will change. Have you encountered this problem? How can I fix it?

Looking forward to your reply

**Comment by Echo0125** [comment]
I apologize for the late response. I've also noticed this issue and I think it might be due to the addition of new parameters altering the distribution of parameter initialization. I suggest not manually adding unnecessary parameters during training, to avoid affecting the performance.
