### ISSUE TITLE
can't find the module 'rekognition_online_action_detection'

### ISSUE THREAD

**Issue by chcchc97** [Echo0125/Memory-and-Anticipation-Transformer#3]
Hi! Why i can't find the module 'rekognition_online_action_detection'?
![516a0074fa58518de09f5b0451ab55f](https://github.com/Echo0125/Memory-and-Anticipation-Transformer/assets/60684460/d7b9fb95-2c62-4b1e-8d4b-49a4d1e2b1d2)

**Comment by chcchc97** [comment]
Thank you! I have solved this problem!

**Comment by jun297** [comment]
@Chenhongchang How did you resolve it?

**Comment by chcchc97** [comment]
> @Chenhongchang How did you resolve it?

Hi! you can add you path in the four line of code, which is sys.path.append(“/path/to/src”).
