### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by chcchc97** [Echo0125/Memory-and-Anticipation-Transformer#7]
Sorry! I have another question about the feature extraction. Because I want to apply MAT to other datasets, so I try to extract the features by myself. As section 5.2 Implementation details, "extract the frames at 4 FPS for training and validation". I have resample the videos at 24 FPS and extract RGB and flow(视频帧和光流) using [mmaction2](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md) But I don't know how to set the video chunk size to 6. How could you do that and are there any tools in mmaction2 can help to realize this step?

**Comment by Echo0125** [comment]
You can set the **clip_interval = 6** in [tsn_extract_rgb_feat_config.py](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/tsn_extract_rgb_feat_config.py).

**Comment by chcchc97** [comment]
> You can set the **clip_interval = 6** in [tsn_extract_rgb_feat_config.py](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/tsn_extract_rgb_feat_config.py).

thank you! I will try it.
