### ISSUE TITLE
FUTURE_SECONDS and ANTICIPATION_SECONDS

### ISSUE THREAD

**Issue by wssxjtu** [Echo0125/Memory-and-Anticipation-Transformer#9]
The code shows FUTURE_SECONDS is 12, ANTICIPATION_SECONDS is 2, and fps is 4.

However, the ablation experiment Figure 5 indicates that the performance published in the article is achieved when the anticipation length is 24 seconds.

Which of FUTURE_SECONDS and ANTICIPATION_SECONDS controls the anticipation length?

Why does that variable represent the time domain of 24 seconds?

Thanks for your reply.

**Comment by Prism-hua** [comment]
@wssxjtu Sorry to bother, have you find out the answer for that question? I have the same problem with you.

**Comment by FELIXFENG2019** [comment]
I am also confused about the difference between FUTURE_SECONDS and ANTICIPATION_SECONDS. Could anyone share the answer?
